name: 6-hour Archive

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Archive URLs
      run: |
        archival_urls=(
          "https://www.mecabricks.com/en/library/renderings"
          "https://www.mecabricks.com"
        )

        for url in "${archival_urls[@]}"; do
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
              break
            else
              ((retry_counter++))
              echo "Failed to archive main page: $url. Retrying..."
            fi
          done || true

          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done || true
          done
        done
