name: auto-archive

on:
  discussion_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create virtual environment
        run: pyenv init -y
        env:
          PYTHON_VERSION: "3.9"

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Install PyPy
        run: |
          source venv/bin/activate
          pip install pypy

      - name: Execute PyPy script
        run: |
          source venv/bin/activate
          pypy discussion_archiver.py
