name: auto-archive

on:
  discussion_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt-get update

      - name: Install libcurl and libxml2 development packages
        run: sudo apt-get install libcurl4-openssl-dev libxml2-dev

      - name: Build C program
        run: |
          gcc -o archiver archiver.c -lcurl -lxml2 -lhtml2

      - name: Execute C program
        run: |
          ./archiver
