name: auto-archive

on:
  discussion_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Execute python script
        run: /opt/hostedtoolcache/Python/3.11.4/x64/bin/python discussion_archiver.py
