name: auto-archive

on:
  discussion_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests beautifulsoup4
        
      - name: Execute python script
      - uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9' 
      - run: python discussion_archiver.py
