name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs
      run: |
        IFS=$'\n' read -d '' -ra urls <<< "${{ github.event.inputs.urls }}"
        for url in "${urls[@]}"; do
          # Use the URL in your archiving process (replace the following line with your archiving command)
          echo "Archiving $url"
          # Replace the following line with your archiving command
          curl -sS "https://web.archive.org/save/$url"
        done
