name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs
      run: |
        archival_urls=(${{ github.event.inputs.urls }})
        echo "========== URLs archived =========="
        for url in "${archival_urls[@]}"; do
          echo "Archiving $url"
          
          # Save the main content
          curl -sS "https://web.archive.org/save/$url" > /dev/null
          
          # Save outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            echo "Archiving outlink: $outlink"
            curl -sS "https://web.archive.org/save/$outlink" > /dev/null
          done
        done
