name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Archive URLs and Update Counter
      run: |
        archival_urls=($(echo "${{ github.event.inputs.urls }}"))

        # Initialize counter
        counter=0

        for url in "${archival_urls[@]}"; do
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
              ((counter++))  # Increment counter on successful archive
              break
            else
              ((retry_counter++))
              echo "Failed to archive main page: $url. Retrying..."
            fi
          done || true

          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                ((counter++))  # Increment counter on successful archive
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done || true
          done
        done

        # Update total count
        current_count=$(<total_url_count.txt)
        new_count=$((current_count + counter))
        echo $new_count > total_url_count.txt

        # Commit and push changes
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add total_url_count.txt
        git commit -m "🤖 Update total URL count"
        git push origin main
