name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs
      run: |
        archival_urls=(${{ github.event.inputs.urls }})
        echo "========== URLs archived =========="
        for url in "${archival_urls[@]}"; do
          echo "$url"
          curl -sS "https://web.archive.org/save/$url" > /dev/null
        done
