name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Archive URLs
      run: |
        archival_urls=(${{ github.event.inputs.urls }})
        
        for url in "${archival_urls[@]}"; do
          # Replace each "&" with "%26"
          encoded_url=$(echo "$url" | sed 's/&/%26/g')
    
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            curl -sS "https://web.archive.org/save/$encoded_url" > /dev/null && break
            ((retry_counter++))
          done || true  # Ignore errors
      
          # Retry loop for outlinks
          curl -sS "$encoded_url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            # Replace each "&" with "%26"
            encoded_outlink=$(echo "$outlink" | sed 's/&/%26/g')
      
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$encoded_outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
              fi
            done
  
            sleep 8s
          done || true  # Ignore errors
  
          sleep 8s
        done
