name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs
      run: |
        archival_urls=(${{ github.event.inputs.urls }})
        
        for url in "${archival_urls[@]}"; do
          echo "Archiving given page: $url"
    
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
            ((retry_counter++))
          done
      
          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            echo "Archiving outlink: $outlink"
      
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done
          done || true  # Ignore errors in the outlink archiving process
        done
