name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive_first_batch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs (First Batch)
      run: |
        archival_urls=($(
          IFS=$'\n'   # Set the Internal Field Separator to newline
          echo "${{ github.event.inputs.urls }}" | sed -n '1,20'
        ))
        for url in "${archival_urls[@]}"; do
          echo "Archiving given page: $url"
    
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
            ((retry_counter++))
          done
      
          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            echo "Archiving outlink: $outlink"
      
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done

            sleep 8s
          done || true  # Ignore errors in the outlink archiving process

          sleep 8s
        done

  archive_second_batch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs (Second Batch)
      run: |
        archival_urls=($(
          IFS=$'\n'   # Set the Internal Field Separator to newline
          echo "${{ github.event.inputs.urls }}" | sed -n '21,40p'
        ))
        for url in "${archival_urls[@]}"; do
          echo "Archiving given page: $url"
    
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
            ((retry_counter++))
          done
      
          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            echo "Archiving outlink: $outlink"
      
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done

            sleep 8s
          done || true  # Ignore errors in the outlink archiving process

          sleep 8s
        done

  archive_third_batch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs (Third Batch)
      run: |
        archival_urls=($(
          IFS=$'\n'   # Set the Internal Field Separator to newline
          echo "${{ github.event.inputs.urls }}" | sed -n '41,60p'
        ))
        for url in "${archival_urls[@]}"; do
          echo "Archiving given page: $url"
    
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
            ((retry_counter++))
          done
      
          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            echo "Archiving outlink: $outlink"
      
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done

            sleep 8s
          done || true  # Ignore errors in the outlink archiving process

          sleep 8s
        done
