name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

concurrency:
  group: archive-workflow
  cancel-in-progress: false

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Archive URLs
      run: |
        archival_urls=(${{ github.event.inputs.urls }})
        total_url_count=0
        total_outlink_count=0

        for url in "${archival_urls[@]}"; do

          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            if curl -sv "https://web.archive.org/save/$url" > /dev/null; then
              break
            fi
            ((retry_counter++))
          done || true  # Ignore errors

          ((total_url_count++))

          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do

            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
              fi
            done

            sleep 8s
            ((total_outlink_count++))
          done || true  # Ignore errors

          sleep 8s
        done

        # Update total counts
        current_url_count=$(<total_url_count.txt)
        new_url_count=$((current_url_count + total_url_count))

        # Commit changes and push to origin
        git add total_url_count.txt
        git commit -m "Update total URL count"
        git push origin
