name: Mass Archive

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'List of URLs (separated by newlines)'
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Archive URLs
      run: |
        archival_urls=(${{ github.event.inputs.urls }})
        
        for url in "${archival_urls[@]}"; do
          echo "Archiving given page: $url"
    
          # Retry loop
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            curl -sS "https://web.archive.org/save/$url" > /dev/null && break
            ((retry_counter++))
          done
        done
